version: "3.9"
services:
  postgres:
    container_name: postgres
    image: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=1234
  postgreskeycloak:
    container_name: postgreskeycloak
    image: postgres
    ports:
      - "5532:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=1234
  keycloak:
    container_name: keycloak
    image: jboss/keycloak:latest
    ports:
      - "8081:8080"
    environment:
      - KEYCLOAK_USER=admin
      - KEYCLOAK_PASSWORD=admin
      - DB_ADDR=postgreskeycloak
      - DB_DATABASE=postgres
      - DB_USER=postgres
      - DB_PASSWORD=1234
  pep-restaurant-backend:
    container_name: pep-restaurant-backend
    build:
      context: ../
      dockerfile: Dockerfile
    env_file:
      - ./docker-compose.env
    depends_on:
      - postgres
      - postgreskeycloak
      - keycloak
    ports:
      - "8080:8080"
    restart: always
